"""Phase A-F: metrics 컬럼, 랭킹/별칭/알림/구독/캘린더 테이블

Revision ID: 5365fe70a19c
Revises: 6f92b865ce85
Create Date: 2026-03-10 08:48:31.838966
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5365fe70a19c'
down_revision = '6f92b865ce85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_calendar_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ece_event_date', 'economic_calendar_events', ['event_date'], unique=False)
    op.create_table('issue_keyword_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alias_keyword', sa.String(length=200), nullable=False),
    sa.Column('canonical_keyword', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_keyword')
    )
    op.create_index('ix_ika_canonical', 'issue_keyword_aliases', ['canonical_keyword'], unique=False)
    op.create_table('issue_rank_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('recent_updates', sa.Integer(), nullable=False),
    sa.Column('tracked_count', sa.Integer(), nullable=False),
    sa.Column('saved_count', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_irs_calculated_rank', 'issue_rank_snapshots', ['calculated_at', 'rank'], unique=False)
    op.create_table('keyword_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'keyword', name='uq_ks_user_keyword')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('MAJOR_UPDATE', 'TRIGGER_UPDATE', 'COMMENT_REPLY', 'KEYWORD_MATCH', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ntf_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('user_alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=True),
    sa.Column('min_importance', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uar_user_active', 'user_alert_rules', ['user_id', 'is_active'], unique=False)
    op.create_table('keyword_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['raw_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['keyword_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_km_subscription_created', 'keyword_matches', ['subscription_id', 'created_at'], unique=False)
    op.add_column('job_runs', sa.Column('metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_runs', 'metrics')
    op.drop_index('ix_km_subscription_created', table_name='keyword_matches')
    op.drop_table('keyword_matches')
    op.drop_index('ix_uar_user_active', table_name='user_alert_rules')
    op.drop_table('user_alert_rules')
    op.drop_index('ix_ntf_user_read_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('keyword_subscriptions')
    op.drop_index('ix_irs_calculated_rank', table_name='issue_rank_snapshots')
    op.drop_table('issue_rank_snapshots')
    op.drop_index('ix_ika_canonical', table_name='issue_keyword_aliases')
    op.drop_table('issue_keyword_aliases')
    op.drop_index('ix_ece_event_date', table_name='economic_calendar_events')
    op.drop_table('economic_calendar_events')
    # ### end Alembic commands ###
